### 회원가입 (고객)

### 이메일 인증 (고객)

### 로그인 (고객)

### 회원 정보 조회 (고객)

### 잔액 변경 (고객)

##################################

### 회원가입 (셀러)

### 로그인 (셀러)
POST http://localhost:8081/signIn/seller
Content-Type: application/json

{
  "email": "youlheek@gmail.com",
  "password": "string"
}


### TODO : scratch