### 로그인 (고객)
POST http://localhost:8081/signIn/customer
Content-Type: application/json

{
  "email": "youleenang@naver.com",
  "password": "string"
}

### 회원 정보 조회 (고객)
GET http://localhost:8081/customer/getInfo
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTm9mRXhGOUJrQVhYYzB2UVB4RUJkMTcrQ2RrUnQwQ3Z3bTFqK3pTdVM4PSIsImp0aSI6ImovVjVCeUxPc2pIWGFoY005ZnU2ZEE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MzcyMTE1NzksImV4cCI6MTczNzI5Nzk3OX0.NU5I1o3e-skheHinEc7ak1QkDz37UBkn8kJhUYImqdo

### 잔액 변경 (고객)
POST http://localhost:8081/customer/balance
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTm9mRXhGOUJrQVhYYzB2UVB4RUJkMTcrQ2RrUnQwQ3Z3bTFqK3pTdVM4PSIsImp0aSI6IjNuMjFOVlRzcStBbFE1K0ZKdVFla0E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MzM4MTA3NjIsImV4cCI6MTczMzg5NzE2Mn0.Mfh4304Ja202qeOgZL7A7wlcsOMnufx1JJXPzvuTA9Y
Content-Type: application/json

{
  "from": "string",
  "message": "string",
  "money": 100000000
}




### 로그인 (셀러)
POST http://localhost:8081/signIn/seller
Content-Type: application/json

{
  "email": "youlheek@gmail.com",
  "password": "string"
}


### TODO : scratch
GET https://api.x.com/1.1/trends/place.json?id=1
Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAEABzAEAAAAAuYMST0QQPxZi%2F1HlCZTcoFrPBQo%3Di76VrHSLG0outaNL0DtDzfxYeRKVndInJwkoK18Gs4UEwsVyWX

###

# curl "https://api.twitter.com/2/trends/by/woeid/1?max_trends=10" -H "Authorization: Bearer $BEARER_TOKEN"
GET https://api.x.com/2/tweets?ids=1261326399320715264,1278347468690915330
Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAEABzAEAAAAAuYMST0QQPxZi%2F1HlCZTcoFrPBQo%3Di76VrHSLG0outaNL0DtDzfxYeRKVndInJwkoK18Gs4UEwsVyWX

###

