### 상품 수정 - 근데 이러면 옵션 수정이랑 뭐가 달라
PUT http://localhost:8082/seller/product
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJXckVlMHB0Tnp5bG1zT1BHMGdKaXpkODhlcS9OcUdoWm5aa00zYjVaSXNNPSIsImp0aSI6ImovVjVCeUxPc2pIWGFoY005ZnU2ZEE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzMzNDY0MDgzLCJleHAiOjE3MzM1NTA0ODN9.gW8ET434GMaEyX6Db0Noh314fIF5X3CpfVtsQoctE_s
Content-Type: application/json

{
  "productId": 11,
  "name": "과일청",
  "description": "string",
  "itmes": [
    {
      "itemId": 32,
      "name": "string",
      "price": 0,
      "count": 0
    }
  ]
}

### 상품 옵션 수정
PUT http://localhost:8082/seller/product/item
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJXckVlMHB0Tnp5bG1zT1BHMGdKaXpkODhlcS9OcUdoWm5aa00zYjVaSXNNPSIsImp0aSI6ImovVjVCeUxPc2pIWGFoY005ZnU2ZEE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzMzNTc5MzY4LCJleHAiOjE3MzM2NjU3Njh9.AOy8qFwPKt-U8DzILOfYd_477m5u30VvrAyI-itJKxM
Content-Type: application/json

{
  "productId": 11,
  "itemId": 32,
  "name": "뭐로할까",
  "price": 0,
  "count": 0
}

### 상품 삭제
DELETE http://localhost:8082/seller/product?productId=10
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJXckVlMHB0Tnp5bG1zT1BHMGdKaXpkODhlcS9OcUdoWm5aa00zYjVaSXNNPSIsImp0aSI6ImovVjVCeUxPc2pIWGFoY005ZnU2ZEE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzMzNTc5MzY4LCJleHAiOjE3MzM2NjU3Njh9.AOy8qFwPKt-U8DzILOfYd_477m5u30VvrAyI-itJKxM
Content-Type: application/json

### 상품 옵션 삭제
DELETE http://localhost:8082/seller/product/item?productItemId=32
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJXckVlMHB0Tnp5bG1zT1BHMGdKaXpkODhlcS9OcUdoWm5aa00zYjVaSXNNPSIsImp0aSI6ImovVjVCeUxPc2pIWGFoY005ZnU2ZEE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzMzNDY0MDgzLCJleHAiOjE3MzM1NTA0ODN9.gW8ET434GMaEyX6Db0Noh314fIF5X3CpfVtsQoctE_s

### 상품 검색
GET http://localhost:8082/search/product?
    name=나이키

### 상품 상세 검색
GET http://localhost:8082/search/product/detail?
    productId=1

### 장바구니 추가
POST http://localhost:8082/customer/cart
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJXckVlMHB0Tnp5bG1zT1BHMGdKaXpkODhlcS9OcUdoWm5aa00zYjVaSXNNPSIsImp0aSI6ImovVjVCeUxPc2pIWGFoY005ZnU2ZEE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzMzODEzMjc1LCJleHAiOjE3MzM4OTk2NzV9.zMxrLO2iqTj8r1RSbz8xxH_phQKCOKKTd0IgCv1zgJ8
Content-Type: application/json

{
  "id": 1,
  "sellerId": 0,
  "name": "나이키",
  "description": "string",
  "items": [
    {
      "id": 1,
      "name": "string",
      "count": 3,
      "price": 0
    }
  ]
}


### 장바구니 확인
GET http://localhost:8082/customer/cart
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTm9mRXhGOUJrQVhYYzB2UVB4RUJkMTcrQ2RrUnQwQ3Z3bTFqK3pTdVM4PSIsImp0aSI6IjNuMjFOVlRzcStBbFE1K0ZKdVFla0E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MzM4MTA3NjIsImV4cCI6MTczMzg5NzE2Mn0.Mfh4304Ja202qeOgZL7A7wlcsOMnufx1JJXPzvuTA9Y

### 주문 (고객)
POST http://localhost:8082/customer/cart/order
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuTm9mRXhGOUJrQVhYYzB2UVB4RUJkMTcrQ2RrUnQwQ3Z3bTFqK3pTdVM4PSIsImp0aSI6IjNuMjFOVlRzcStBbFE1K0ZKdVFla0E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MzM4MTA3NjIsImV4cCI6MTczMzg5NzE2Mn0.Mfh4304Ja202qeOgZL7A7wlcsOMnufx1JJXPzvuTA9Y
Content-Type: application/json

{
  "customerId": 0,
  "products": [
    {
      "id": 1,
      "sellerId": 0,
      "name": "string",
      "description": "string",
      "items": [
        {
          "id": 1,
          "name": "string",
          "count": 2,
          "price": 230980
        }
      ]
    }
  ],
  "messages": [
  ]
}